# Generated by Django 5.2.7 on 2025-10-22 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_funcionario_options_funcionario_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='timestamp_servidor',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
