# Generated by Django 5.2.7 on 2025-10-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_registroponto_timestamp_servidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
