# Generated by Django 5.2.7 on 2025-10-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_registroponto_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroponto',
            name='timestamp_servidor',
        ),
        migrations.AlterField(
            model_name='registroponto',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
