# Generated by Django 5.2.7 on 2025-10-22 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_registroponto_timestamp_servidor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroponto',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
