# Generated by Django 5.2.7 on 2025-10-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_registroponto_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações sobre este registro (ex: falta justificada, atraso, etc.)', max_length=500, null=True, verbose_name='Observações'),
        ),
    ]
